fragment ProjectBlock on ProjectBlockRecord {
  id
  projects {
    id
    date
    link
    title
    hasRepository
    description {
      value
      blocks
    }
    image {
      responsiveImage(imgixParams: { auto: format, w: 300 }) {
        srcSet
        webpSrcSet
        sizes
        src
        width
        height
        aspectRatio
        alt
        title
        base64
      }
    }
  }
}
