fragment CertificationBlock on CertificationBlockRecord {
  id
  certifications {
    id
    link
    badge {
      responsiveImage(imgixParams: { w: 112, h: 112 }) {
        srcSet
        webpSrcSet
        sizes
        src
        width
        height
        aspectRatio
        alt
        title
        base64
      }
    }
    title
    authority
    inProgress
  }
}
