query PagesSlug {
  allPages {
    slug
    _publishedAt
  }
}

query Page($slug: String!) {
  page(filter: { slug: { eq: $slug } }) {
    title
    slug
    footerAnimatedGif {
      responsiveImage(imgixParams: { auto: format }) {
        srcSet
        webpSrcSet
        sizes
        src
        width
        height
        aspectRatio
        alt
        title
        base64
      }
    }
    content {
      value
      blocks {
        __typename
        ...HeroProfileBlock
        ...ImageBlock
        ...TimelineBlock
        ...CertificationBlock
        ...ProjectBlock
      }
    }
    seo {
      title
      description
    }
  }
  common {
    ... on CommonRecord {
      logo {
        responsiveImage(imgixParams: { auto: format, w: 36, h: 36 }) {
          srcSet
          webpSrcSet
          sizes
          src
          width
          height
          aspectRatio
          alt
          title
          base64
        }
      }
      cvFile {
        url
      }
    }
  }
  allPages {
    slug
    title
    hidden
  }
}
