query PagesSlug {
  allPages {
    slug
  }
}

query Page($slug: String!) {
  page(filter: { slug: { eq: $slug } }) {
    title
    slug
    content {
      value
      blocks {
        __typename
        ...HeroProfileBlock
        ...ImageBlock
        ...TimelineBlock
        ...CertificationBlock
      }
    }
  }
  common {
    ... on CommonRecord {
      logo {
        responsiveImage(imgixParams: { auto: format, w: 36, h: 36 }) {
          srcSet
          webpSrcSet
          sizes
          src
          width
          height
          aspectRatio
          alt
          title
          base64
        }
      }
      cvFile {
        url
      }
    }
  }
  allPages {
    slug
    title
    hidden
  }
}
