query PagesSlug {
  allPages {
    slug
  }
}

query Page($slug: String!) {
  page(filter: { slug: { eq: $slug } }) {
    title
    slug
    content {
      value
      blocks {
        __typename
        ...HeroProfileBlock
        ...ImageBlock
        ...TimelineBlock
        ...CertificationBlock
      }
    }
  }
  common {
    ... on CommonRecord {
      logo {
        url
      }
      cvFile {
        url
      }
    }
  }
  allPages {
    slug
    title
    hidden
  }
}
